import Navbar from "@/component/Navbar";
import "./globals.css";
import { ThemeProvider } from "@/component/themeProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-1 flex-col">
        <ThemeProvider  attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
